const GET_ONE_RESTAURANT = 'GET_ONE_RESTAURANT';
const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS';
const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
const GET_RESTAURANT_QUERY = 'GET_RESTAURANT_QUERY';
const GET_FILTER_TYPE = 'GET_FILTER_TYPE';
const GET_ORDER_PARAM = 'GET_ORDER_PARAM';
const EDIT_ONE_RESTAURANT = 'EDIT_ONE_RESTAURANT';
const DELETE_ONE_RESTAURANT = 'DELETE_ONE_RESTAURANT';


module.exports = {
    GET_ALL_RESTAURANTS,
    GET_RESTAURANT_QUERY,
    GET_ONE_RESTAURANT,
    CREATE_ACTIVITY,
    GET_FILTER_TYPE,
    GET_ORDER_PARAM,
    EDIT_ONE_RESTAURANT,
    DELETE_ONE_RESTAURANT
}